### ISSUE TITLE
Add info for Pylint command for Coding and Contribution guidelines

### ISSUE THREAD

**Issue by gggodhwani** [CivicDataLab/hp-fiscal-data-explorer-backend#18]

**Comment by curioswati** [comment]
added guidelines on scoring in this [commit](https://github.com/CivicDataLab/hp-fiscal-data-explorer/wiki/Coding-Guidelines/b1aafc99c1871c18556b6ca673f30cb501c67f54)

**Comment by curioswati** [comment]
Added a wiki page on integrating pylint in the workflow [here](https://github.com/CivicDataLab/hp-fiscal-data-explorer/wiki/Integrate-code-linting-to-your-workflow/66ff0f6f3af96913b8a8aa63be1e33f24b6ae31f)

**Comment by curioswati** [comment]
@gggodhwani please review them once and close the issue if they seem good enough.
