### ISSUE TITLE
Create a wiki page for setting up apache airflow

### ISSUE THREAD

**Issue by curioswati** [CivicDataLab/hp-fiscal-data-explorer-backend#27]

**Comment by curioswati** [comment]
Check this out @shreyaagrawal0809 : https://github.com/CivicDataLab/hp-fiscal-data-explorer/wiki/Setup-Apache-Airflow-on-the-server-for-Crawl-Management
See if  you can follow and then let me know so I'd close the issue.

**Comment by curioswati** [comment]
see this also @shreyaagrawal0809 : https://github.com/CivicDataLab/hp-fiscal-data-explorer/wiki/Scheduling-with-Apache-Airflow:-Resources

**Comment by shreyaagrawal0809** [comment]
:+1:
